# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UADuj75nbYgQHxR9tg4nRZLJvX-56pDw
"""

!pip install flask flask-ngrok huggingface_hub joblib
!pip install flask-ngrok pyngrok --quiet

from flask import Flask, request, render_template_string
from flask_ngrok import run_with_ngrok
from huggingface_hub import hf_hub_download
import numpy as np
import joblib

!ngrok config add-authtoken 2vfCpnlJCTbpxpP6FElMT5Fqdey_81HsFTWdsLBzxEZiiN4f3

REPO_ID = "alihaider-debug/sgd-regression-california-housing"

model = joblib.load(hf_hub_download(repo_id=REPO_ID, filename="model.pkl"))
scaler = joblib.load(hf_hub_download(repo_id=REPO_ID, filename="scaler.pkl"))
poly = joblib.load(hf_hub_download(repo_id=REPO_ID, filename="poly.pkl"))


html_template = """
<!DOCTYPE html>
<html>
<head>
    <title>🏡 House Value Predictor</title>
</head>
<body style="font-family: 'Segoe UI', sans-serif; background: #f4f4f4; text-align: center; margin-top: 50px;">
    <div style="background-color: white; max-width: 500px; margin: auto; padding: 30px; border-radius: 15px; box-shadow: 0 4px 15px rgba(0,0,0,0.1);">
        <h2 style="color: #2e8b57;">California Housing Price Predictor</h2>
        <form method="POST">
            <label style="font-weight: bold;">Median Income:</label><br>
            <input type="number" step="0.01" name="med_inc" required style="width: 90%; padding: 10px; margin: 10px 0; border-radius: 8px; border: 1px solid #ccc;"><br>

            <label style="font-weight: bold;">Average Rooms:</label><br>
            <input type="number" step="0.01" name="ave_rooms" required style="width: 90%; padding: 10px; margin: 10px 0; border-radius: 8px; border: 1px solid #ccc;"><br>

            <input type="submit" value="Predict" style="background-color: #2e8b57; color: white; padding: 10px 20px; border: none; border-radius: 8px; cursor: pointer;">
        </form>
        {% if prediction %}
        <h3 style="color: #444; margin-top: 20px;">Predicted House Value: ${{ prediction }}</h3>
        {% endif %}
    </div>
</body>
</html>
"""


from flask import Flask, request, render_template_string
from pyngrok import ngrok
import numpy as np

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def home():
    prediction = None
    if request.method == "POST":
        med_inc = float(request.form["med_inc"])
        ave_rooms = float(request.form["ave_rooms"])
        input_data = np.array([[med_inc, ave_rooms]])
        input_poly = poly.transform(input_data)
        input_scaled = scaler.transform(input_poly)
        prediction = round(model.predict(input_scaled)[0], 2)
    return render_template_string(html_template, prediction=prediction)

# Expose Flask app to the internet
public_url = ngrok.connect(5000)
print(f" * ngrok tunnel: {public_url}")
app.run()