# -*- coding: utf-8 -*-
"""inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GI4CeU6nXrvz2GrOEs9h_bC_2dg7px6
"""

# inference.py

from huggingface_hub import hf_hub_download
import joblib
import numpy as np

# Load all components from Hugging Face repo
REPO_ID = "alihaider-debug/sgd-regression-california-housing"

model_path = hf_hub_download(repo_id=REPO_ID, filename="model.pkl")
scaler_path = hf_hub_download(repo_id=REPO_ID, filename="scaler.pkl")
poly_path = hf_hub_download(repo_id=REPO_ID, filename="poly.pkl")

# Load the saved components
model = joblib.load(model_path)
scaler = joblib.load(scaler_path)
poly = joblib.load(poly_path)

# Define prediction function
def predict_house_value(feature_1, feature_2):
    try:
        # Accept input and reshape
        input_array = np.array([[feature_1, feature_2]])

        # Apply polynomial transformation and scaling
        input_poly = poly.transform(input_array)
        input_scaled = scaler.transform(input_poly)

        # Make prediction
        prediction = model.predict(input_scaled)[0]

        return f"Predicted Median House Value: ${prediction:.2f}"

    except Exception as e:
        return f"Error during prediction: {str(e)}"

# Example usage (This will only run if the script is called directly)
if __name__ == "__main__":
    print("🏡 California House Value Predictor")
    try:
        f1 = float(input("Enter Feature 1 (e.g. MedInc): "))
        f2 = float(input("Enter Feature 2 (e.g. AveRooms): "))
        result = predict_house_value(f1, f2)
        print(result)
    except ValueError:
        print("❌ Invalid input. Please enter numerical values.")